### ISSUE TITLE
Add site icon at the title position

### ISSUE THREAD

**Issue by EBEREGIT** [EBEREGIT/Geo-Search#43]

**Comment by chancesmith** [comment]
👋 @EBEREGIT, is this the logo mark you want as a favicon?

![Screenshot 2019-11-27 06 03 59](https://user-images.githubusercontent.com/4466585/69722151-fdca5780-10db-11ea-8d8f-b8fbd23118bf.png)

**Comment by EBEREGIT** [comment]
Yes but this project has been restricted to a number of persons.

However, I will be opening a new open source Project very soon.

If you will like to be contacted to contribute to the project?

Please leave your contact information and I will keep you updated.

Thank you for your interest in this project.

**Comment by chancesmith** [comment]
👍 No problem! My email is in my GitHub bio.
